### ISSUE TITLE
make error while building ISPC components

### ISSUE THREAD

**Issue by tatz-murakami** [simeks/deform#134]
`python setup.py install --use-cuda --use-ispc --debug` returns the following error during make.

> [ 74%] Built target yaml-cpp
[ 75%] Building ISPC components
Error: Multiple input files specified on command line: " -g" and 
       "/home/tmurakami/app/deform/src/deform_lib/ispc/cost_function.ispc". 
make[2]: *** [src/deform_lib/ispc/CMakeFiles/ispc_target.dir/build.make:73: src/deform_lib/ispc/ispc_lib.o] Error 255
make[1]: *** [CMakeFiles/Makefile2:1406: src/deform_lib/ispc/CMakeFiles/ispc_target.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by simeks** [comment]
Seems to be some issue with CMake and ISPC, should be fixed in 3d6ab6f3c398ef18343b77c84874cec64b918e57.

**Comment by tatz-murakami** [comment]
Installed. How can I use GPU from python? I could see it is running without using GPU.

```
import pydeform

settings = {
    'pyramid_levels':6,
    'pyramid_stop_level': 1,
    'block_size': [64,64,64],
    'block_energy_epsilon':1e-7,
    'max_iteration_count':-1,
    'constraints_weight':1000.0,
    'image_slots': 
    [
        {
            'resampler': 'gaussian',
            'normalize': True,
            'cost_function': 
            [
                {
                    'function':'ncc',
                    'weight':1.0,
                    'radius':7,
                    'window':'cube'
                }
            ]
        }
    ]
}

df = pydeform.register(
    fixed,
    moving,
    settings=settings,
    log='deform.log',
    log_level=pydeform.LogLevel.Verbose,
    num_threads=48
)
```

**Comment by simeks** [comment]
You should be able to just add the argument `use_gpu=True` to the `pydeform.register` call to have it running with GPU-support.

I realized now though that I don't think the `window: cube` mode is available on the GPU so in your case it would default to `window: sphere`.

**Comment by tatz-murakami** [comment]
Problem solved. Thank you.
